### ISSUE TITLE
POST Bulk Assign for Call Queues Pointing to GLIP and not Call Queues Object

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-csharp-client#49]
ISSUE: When trying to POST to update the CallQueue Members I get "Call failed with status code 400 (Bad Request)". 

API Using: ringCentral.Restapi().Account("~").CallQueues(groupId.ToString()).BulkAssign().Post(requestBody);

When I started to look into the BulkAssign() I noticed the POST object was explicitly looking at the blow code:
`    public class BulkAssignPath : PathSegment
    {
        protected override string Segment { get; }

        public Task<GlipGroupInfo> Post();
        public Task<GlipGroupInfo> Post(object parameters);
        public Task<GlipGroupInfo> Post(EditGroupRequest parameters);
    }`

Can I get some assistance or understanding why I can't POST for CallQueues?

RingCentral API Reference https://developer.ringcentral.com/api-reference#Account-Provisioning-updateCallQueueGroup

**Comment by tylerlong** [comment]
Hi @AndyHaas whenever there is an exception caused by server, catch it and print the response message from server: https://github.com/ringcentral/ringcentral-csharp-client#exception-handling

```csharp
catch (FlurlHttpException fhe)
{
    string errorMessage = fhe.GetResponseString();
    Console.WriteLine(errorMessage);
```

**Comment by tylerlong** [comment]
> what it should be based on the API Reference

Which API reference do you mean? Send me the link

Please check the error message first. Mostly like you will know how to solve the issue after reading error message.

**Comment by AndyHaas** [comment]
@tylerlong here is the exception message. Sorry about not including this
`Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/call-queues/210164004/bulk-assign
   at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RingCentral.RestClient.<Post>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RingCentralAPI.Controllers.CallQueueMemberController.<Post>d__0.MoveNext() in C:\Enterprise\Internal\RingCentral\Relese 3.1\RingCentralAPI\RingCentralAPI\Controllers\CallQueueMemberController.cs:line 71
`

**Comment by AndyHaas** [comment]
> > what it should be based on the API Reference
> 
> Which API reference do you mean? Send me the link
> 
> Please check the error message first. Mostly like you will know how to solve the issue after reading error message.

Here is the API Reference I was mentioning

RingCentral API Reference https://developer.ringcentral.com/api-reference#Account-Provisioning-updateCallQueueGroup

**Comment by tylerlong** [comment]
@AndyHaas  stacktrace is useless. Print the error message please:

```cs
catch (FlurlHttpException fhe)
{
    string errorMessage = fhe.GetResponseString();
    Console.WriteLine(errorMessage);
```

**Comment by tylerlong** [comment]
We do not maintain this SDK any more. Every user should use [RingCentral.NET](https://github.com/ringcentral/ringcentral.net)
